// lib/countryUtils.ts

/**
 * Get a 3-letter country code from a country name
 */
export function getCountryCode(country?: string): string {
  if (!country) return 'INT';
  
  const countryMap: Record<string, string> = {
    'United States': 'USA',
    'Russia': 'RUS',
    'Brazil': 'BRA',
    'United Kingdom': 'GBR',
    'Canada': 'CAN',
    'Australia': 'AUS',
    'Mexico': 'MEX',
    'Poland': 'POL',
    'Ireland': 'IRL',
    'France': 'FRA',
    'Netherlands': 'NLD',
    'Sweden': 'SWE',
    'Denmark': 'DNK',
    'Norway': 'NOR',
    'Finland': 'FIN',
    'Germany': 'DEU',
    'Austria': 'AUT',
    'Switzerland': 'CHE',
    'Italy': 'ITA',
    'Spain': 'ESP',
    'Portugal': 'PRT',
    'Belgium': 'BEL',
    'Japan': 'JPN',
    'China': 'CHN',
    'South Korea': 'KOR',
    'Thailand': 'THA',
    'Philippines': 'PHL',
    'Kazakhstan': 'KAZ',
    'Uzbekistan': 'UZB',
    'Azerbaijan': 'AZE',
    'Georgia': 'GEO',
    'Armenia': 'ARM',
    'Ukraine': 'UKR',
    'Belarus': 'BLR',
    'Kyrgyzstan': 'KGZ',
    'Tajikistan': 'TJK',
    'New Zealand': 'NZL',
    'Argentina': 'ARG',
    'Chile': 'CHL',
    'Colombia': 'COL',
    'Venezuela': 'VEN',
    'Peru': 'PER',
    'Ecuador': 'ECU',
    'Uruguay': 'URY',
    'Cuba': 'CUB',
    'South Africa': 'ZAF',
    'Nigeria': 'NGA',
    'Egypt': 'EGY',
    'Morocco': 'MAR',
    'Tunisia': 'TUN',
    'Algeria': 'DZA',
    'Cameroon': 'CMR',
    'Israel': 'ISR',
    'Turkey': 'TUR',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Afghanistan': 'AFG',
    'Pakistan': 'PAK',
    'India': 'IND',
    'Bangladesh': 'BGD',
    'Sri Lanka': 'LKA',
    'Nepal': 'NPL',
    'Mongolia': 'MNG',
    'Vietnam': 'VNM',
    'Indonesia': 'IDN',
    'Malaysia': 'MYS',
    'Singapore': 'SGP',
    'Unknown': 'INT',
  };

  return countryMap[country] || 'INT';
}
